/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca.ulaval.glo2004.gui;

import ca.ulaval.glo2004.gui.Enum.TypePolygone;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Antoine
 */
public class PopupColor extends javax.swing.JFrame implements ChangeListener {

    private MainWindow mainWindow;
    private ElementCouleur elementCouleur;
    private TypePolygone type;
    private HashMap<TypePolygone, Color> currentCouleurs;
    
    /**
     * Creates new form popColor
     */
    public PopupColor(MainWindow mainWindow, ElementCouleur elementCouleur) {
        initComponents();
        
        this.mainWindow = mainWindow;
        this.elementCouleur = elementCouleur;
        
        jColorChooser.getSelectionModel().addChangeListener(this);
        jColorChooser.setPreviewPanel(new JPanel());
        
        type = TypePolygone.MUR;
        currentCouleurs = (HashMap<TypePolygone, Color>) elementCouleur.getCouleurs().clone();
        
        AbstractColorChooserPanel[] panels = jColorChooser.getChooserPanels();
        for (AbstractColorChooserPanel accp : panels) {
            if(!accp.getDisplayName().equals("Swatches")) {
                jColorChooser.removeChooserPanel(accp);
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelColor = new javax.swing.JPanel();
        jLabelDesciption = new javax.swing.JLabel();
        jComboBoxElement = new javax.swing.JComboBox<>();
        jColorChooser = new javax.swing.JColorChooser();
        jBoutonsPanel = new javax.swing.JPanel();
        jBoutonSauvegarder = new javax.swing.JButton();
        jBoutonAnnuler = new javax.swing.JButton();

        setTitle("Édition de couleur");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelColor.setLayout(new java.awt.GridBagLayout());

        jLabelDesciption.setText("Élément à modifier :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelColor.add(jLabelDesciption, gridBagConstraints);

        jComboBoxElement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mur", "Porte", "Fenêtre", "Prise", "Retour Air" }));
        jComboBoxElement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxElementItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelColor.add(jComboBoxElement, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelColor.add(jColorChooser, gridBagConstraints);

        jBoutonSauvegarder.setText("Sauvegarder");
        jBoutonSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoutonSauvegarderActionPerformed(evt);
            }
        });
        jBoutonsPanel.add(jBoutonSauvegarder);

        jBoutonAnnuler.setText("Annuler");
        jBoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoutonAnnulerActionPerformed(evt);
            }
        });
        jBoutonsPanel.add(jBoutonAnnuler);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        panelColor.add(jBoutonsPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        resetCouleur();
    }//GEN-LAST:event_formWindowClosing

    private void jComboBoxElementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxElementItemStateChanged
        type = TypePolygone.fromString(jComboBoxElement.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxElementItemStateChanged

    private void jBoutonSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoutonSauvegarderActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBoutonSauvegarderActionPerformed

    private void jBoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoutonAnnulerActionPerformed
        resetCouleur();
    }//GEN-LAST:event_jBoutonAnnulerActionPerformed

    @Override
    public void stateChanged(ChangeEvent e) {
        Color newColor = jColorChooser.getColor();
        mainWindow.setWantedColor(type, newColor);
        
    }
    
    private void resetCouleur() {
        for (TypePolygone type : currentCouleurs.keySet()) {
            mainWindow.setWantedColor(type, currentCouleurs.get(type));
        }
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoutonAnnuler;
    private javax.swing.JButton jBoutonSauvegarder;
    private javax.swing.JPanel jBoutonsPanel;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JComboBox<String> jComboBoxElement;
    private javax.swing.JLabel jLabelDesciption;
    private javax.swing.JPanel panelColor;
    // End of variables declaration//GEN-END:variables

}
